### PR TITLE
Updated syntax to work with Postmark's Spamcheck API

### PR DESCRIPTION
**Pull request by connorqmoore**

### CODE REVIEW

**Comment by FabioFleitas** [comment]
Hi @connorqmoore thanks for the contribution. It seems like the PR mainly changed the code style. Does the current code from `master` not work?

**Comment by connorqmoore** [comment]
Yeah I was confused why but this syntax change seemed to make the API stop
throwing an error. Unfortunately I ended up changing around the content and
it looks like something stopped working on their API. No matter what I put
for email content it returns a score of 7.9...

On Monday, May 9, 2016, Fabio Fleitas notifications@github.com wrote:

> Hi @connorqmoore https://github.com/connorqmoore thanks for the
> contribution. It seems like the PR mainly changed the code style. Does the
> current code from master not work?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/Tesorio/spamcheck-python/pull/1#issuecomment-217931625

## 

Connor Moore
B.S. in Information Systems 2017
Carnegie Mellon University

**Comment by FabioFleitas** [comment]
I keep getting a 500 error on both `master` branch and your PR. Not sure how to diagnose the issue.

**Comment by connorqmoore** [comment]
Hmmm. Yeah I think something is up with the API. O well.

On Tuesday, May 10, 2016, Fabio Fleitas notifications@github.com wrote:

> I keep getting a 500 error on both master branch and your PR. Not sure
> how to diagnose the issue.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/Tesorio/spamcheck-python/pull/1#issuecomment-218245192

## 

Connor Moore
B.S. in Information Systems 2017
Carnegie Mellon University

**Pull request closed without merging**
